language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install psycopg2-binary

script:
  - psql -c 'create database stackoverflow;' -U postgres
  - python migration.py
  - coverage run -m pytest
  - py.test --cov=project

after_success:
  - coveralls